server:
  port: 8080
  servlet-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://172.21.139.179:3306/eacoophp
    username: ENC(4ceffAI9QYMd0BPknro0Mw==)
    password: ENC(zgcm9P3zKuZL53MS9iHf8ylTxFzwoVbJPzsHCUxZIgQ=)
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

    ### 数据源的其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    ### 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#  redis:
#    # Redis服务器地址
#    host: 172.21.139.179
#    # Redis服务器连接密码（默认为空）
#    password: ENC(PZMBgPovjv/zyXSXlpPKP+Pd5QsA/sUC)
#    # Redis服务器连接端口
#    port: 6379
#    # Redis数据库索引（默认为0）
#    database: 0
#    # 连接超时时间（毫秒）
#    timeout: 5000
#    # 连接池最大连接数（使用负值表示没有限制）
#    pool:
#      max-active: 8
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
#      # 连接池中的最大空闲连接
#      max-idle: 8
#      # 连接池中的最小空闲连接
#      min-idle: 0

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

# 配置jasypt安全框架加解密用的“盐”
jasypt:
  encryptor:
    password: G0CvDz7oJn6

# pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: rue
  params=count: countSql


wchm:
  # 服务器文件相对路径
  update-relative: /upload/
  # 服务器文件绝对路径
  update-absolutely: /usr/local/website/upload/
  # 上传图片相对路径
  update-image-relative: /upload/images/
  # 上传图片绝对路径
  update-image-absolutely: /usr/local/website/upload/images/
  # 白皮书文件地址
  paper-absolutely: /usr/local/website/upload/paper/
  # 公司钱包地址 测试地址
  company-address: "0x9dC45C9BaE4D45aD8B45F492BbC51D7834EF170C"
  # 公司账户私钥 测试私钥
  company-pri-key: ""
  # PCT代币地址
  contract-address: "0x183630c3AfA08957E588eaa26b748cc5C2D42DC6"
  # 转账 method-id
  method-id: "0xa9059cbb000000000000000000000000"
  # 第三方请求以太坊接口数据访问地址
  infura-api: "https://mainnet.infura.io/v3/c783bc77104c4b2d8d7cca07e85dcbc5"
  # 查询钱包地址交易记录api地址
  address-transactions-url: "https://api.etherscan.io/api?module=account&action=tokentx&contractaddress=${wchm.contract-address}&startblock=0&endblock=99999999&page=[pageNum]&offset=[pageSize]&sort=desc&address=[address]&apikey=RAUWFA7NCA5H2IMDJ4V5GYK6ARVTA7Y23U"
  # keystore文件存放地址
  keystore-address: "/usr/local/website/upload/keystore/pct/UTC--2018-11-06T01-21-53.686Z--252a5761cbe1e0711eec88ad90d333fa5e1fb2f6"
  # keystore文件密码
  keystore-password: "123456789"